require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/npcs", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # NPC. As you add validations to NPC, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { age: "a child" }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # NPCsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /v1/index" do
    it "renders a successful response" do
      NPC.create! valid_attributes
      get v1_npcs_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /v1/random" do
    it "renders a successful response" do
      get random_v1_npcs_url, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /v1/show" do
    it "renders a successful response" do
      npc = NPC.create! valid_attributes
      get v1_npc_url(npc), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /v1/create" do
    context "with valid parameters" do
      it "creates a new NPC" do
        expect {
          post v1_npcs_url,
               params: { npc: valid_attributes }, headers: valid_headers, as: :json
        }.to change(NPC, :count).by(1)
      end

      it "renders a JSON response with the new npc" do
        post v1_npcs_url,
             params: { npc: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NPC" do
        expect {
          post v1_npcs_url,
               params: { npc: invalid_attributes }, as: :json
        }.to change(NPC, :count).by(0)
      end

      it "renders a JSON response with errors for the new npc" do
        post v1_npcs_url,
             params: { npc: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /v1/update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested npc" do
        npc = NPC.create! valid_attributes
        patch v1_npc_url(npc),
              params: { npc: invalid_attributes }, headers: valid_headers, as: :json
        npc.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the npc" do
        npc = NPC.create! valid_attributes
        patch v1_npc_url(npc),
              params: { npc: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the npc" do
        npc = NPC.create! valid_attributes
        patch v1_npc_url(npc),
              params: { npc: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /v1/destroy" do
    it "destroys the requested npc" do
      npc = NPC.create! valid_attributes
      expect {
        delete v1_npc_url(npc), headers: valid_headers, as: :json
      }.to change(NPC, :count).by(-1)
    end
  end
end
